# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dubaidemo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_4160b2f0c9034d4b9cd9ed36cd98baee }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0790dcb469154eb8b7de73888ec579ad }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4160b2f0c9034d4b9cd9ed36cd98baee }}/maheboobdev/weatherapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dubaidemo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a9c5c503803e4c9dabaa3d96b4ed3717 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4160b2f0c9034d4b9cd9ed36cd98baee }}/maheboobdev/weatherapp:${{ github.sha }}'